### ISSUE TITLE
2D?

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [tomankirilov/VPainter#10]
2D vertex colors are edited using a list, so a tool would be greatly beneficial. Though in some ways 3D polygonal is better because with 2D AA isn't always available (in 3.1+ it's broken if HDR is on, not available in web. Also AA is not available at all for polygons in 4.0a last I checked).

However in 2D you can animate polygons directly, both vertex positions and vertex colors... and frame or tweened style for either. So over all there's a wide possibility for style.

I similarly would like more capability for dynamic vertex colors in 3D, but I do understand it's likely beyond the scope here. Or it might not even be viable to do. For more info, [a thread here](https://www.reddit.com/r/godot/comments/wxmw1z/dynamic_vertex_colors_in_3d/).

**Comment by tomankirilov** [comment]
This is actually a good idea.
I experimented a little with doing a simple terrain with vertex color for 2d and it can make a nice terrain for 2d games.
Would love to try if I manage to get some free time.
