### ISSUE TITLE
Painting object with low number of vertices

### ISSUE THREAD

**Issue by MossFrog** [tomankirilov/VPainter#5]
Is there any way to paint objects with a low number of vertices? Im trying to paint a basic map consisting of cubes and prisms but the Vpainter only paints when hovering over a vertex and for example for a cube has only 8 points where you can paint

**Comment by tomankirilov** [comment]
The idea of the addon is that it paints vertex color. So you need vertices to paint on. 
You can try subdividing the mesh if you need more detail. It should still be lighter than a whole new texture.
