### ISSUE TITLE
Submit to the Godot asset library

### ISSUE THREAD

**Issue by Calinou** [tomankirilov/VPainter#6]
Could you look into submitting this add-on to the [Godot asset library](https://godotengine.org/asset-library/)? This will make it easier to discover. Thanks in advance :slightly_smiling_face:

**Comment by tomankirilov** [comment]
I will. Need to check how that works :)

**Comment by tomankirilov** [comment]
It's done!

**Comment by Calinou** [comment]
Thanks :slightly_smiling_face: 

The asset is now approved: https://godotengine.org/asset-library/asset/856

PS: The asset library can fetch YouTube thumbnails automatically. No need to add a thumbnail manually for YouTube videos. (Also, the editor's asset library integration can't display GIFs yet.)
